error: let conversion from RawLog to Log fail
Rework error handling, rename custom type to avoid name clashes with std
and allow conversion to fail

Signed-off-by: Jerome Brunet <jbrun3t@gmail.com>